/**
 * The GitHub Actions workflow a talk deploys with (spec §14): check, then deploy via OIDC, with
 * no access key anywhere. It is generated rather than copied, because where the talk sits in its
 * repository and how that repository checks itself differ from project to project, and a copied
 * file would have to be edited by hand — exactly the step the bootstrap checks cannot see.
 */

/** What the generator needs to know about the repository. */
export interface WorkflowInput {
  /** The talk's folder relative to the repository root, `""` when the talk is the root. */
  talkDir: string;
  /** The package manager the repository's lockfile belongs to. */
  packageManager: "pnpm" | "npm";
  /** Whether the repository root has its own `check` script, which then gates the deploy. */
  rootCheck: boolean;
  /** Whether that check runs Playwright, which needs its browser installed first. */
  playwright: boolean;
  /** A Node version file at the root, e.g. `.nvmrc`; otherwise Node 24. */
  nodeVersionFile?: string;
  /** The GitHub environment the bootstrap's trust policy names. */
  environment: string;
  /** The branch the environment admits. */
  branch: string;
}

/** A GitHub Actions expression that reads a secret of the job's environment. */
const secret = (name: string) => `$${"{{"} secrets.${name} }}`;

/** The workflow as YAML. */
export function deployWorkflow(input: WorkflowInput): string {
  const exec = input.packageManager === "pnpm" ? "pnpm exec" : "npx";
  const inTalk = input.talkDir ? `\n        working-directory: ${input.talkDir}` : "";
  const node = input.nodeVersionFile
    ? `node-version-file: ${input.nodeVersionFile}`
    : "node-version: 24";
  const install = input.packageManager === "pnpm" ? "pnpm install --frozen-lockfile" : "npm ci";
  const check = input.rootCheck
    ? [
        ...(input.playwright
          ? [`      - run: ${exec} playwright install --with-deps chromium${inTalk}`]
          : []),
        `      - run: ${input.packageManager === "pnpm" ? "pnpm check" : "npm run check"}`,
      ]
    : [`      - run: ${exec} slidesend check${inTalk}`];
  return [
    "name: deploy",
    "",
    "# Generated by `slidesend workflow`. Checks the talk and deploys it to AWS.",
    "#",
    "# Credentials come from OIDC: the job assumes the deploy role that `slidesend bootstrap",
    "# --deploy` created, whose trust policy admits only this repository in the environment",
    `# "${input.environment}". The environment admits only ${input.branch}. No access key exists.`,
    "",
    "on:",
    "  push:",
    `    branches: [${input.branch}]`,
    "  workflow_dispatch:",
    "",
    "permissions:",
    "  contents: read",
    "  id-token: write # OIDC: assume the deploy role",
    "",
    "# One deploy at a time, and never cancel one halfway: a stack update interrupted by the next",
    "# push leaves CloudFormation rolling back while the new run waits for it.",
    "concurrency:",
    "  group: deploy",
    "  cancel-in-progress: false",
    "",
    "jobs:",
    "  deploy:",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 60",
    `    environment: ${input.environment}`,
    "    steps:",
    "      - uses: actions/checkout@v7",
    ...(input.packageManager === "pnpm" ? ["      - uses: pnpm/action-setup@v6"] : []),
    "      - uses: actions/setup-node@v7",
    "        with:",
    `          ${node}`,
    `          cache: ${input.packageManager}`,
    `      - run: ${install}`,
    ...check,
    "      - uses: aws-actions/configure-aws-credentials@v6",
    "        with:",
    `          role-to-assume: ${secret("AWS_DEPLOY_ROLE")}`,
    `          aws-region: ${secret("AWS_REGION")}`,
    "          # The role's maximum, beyond the job's timeout: a slow deploy hits the timeout",
    "          # rather than credentials that expired halfway through a stack update.",
    "          role-duration-seconds: 7200",
    `      - run: ${exec} slidesend deploy --region ${secret("AWS_REGION")}${inTalk}`,
    "",
  ].join("\n");
}
