/**
 * What `aws-blocks` is outside AWS mode: nothing. Its client is generated by `npm run dev` and
 * `npm run build`; a local run has none, so vite.config.ts points the import here instead.
 */
export const slidesend = undefined;
